app/routes/project_routes.py
from flask import Blueprint, redirect, url_for, render_template, request
from flask_login import login_required, current_user

from app.forms import SetProjectForm
from app.services.project_services import ProjectServices

pj_bp = Blueprint("project", __name__)


@pj_bp.route("/projects")
def get_all_projects():
    page = request.args.get("page",1,type=int)
    projects = ProjectServices.get_all_projects_by_page(page)
    return render_template("project.html", projects=projects)


@pj_bp.route("/add-project", methods=["GET", "POST"])
@login_required
def add_project():
    form = SetProjectForm()
    if form.validate_on_submit():
        new_project = ProjectServices.add_project(
            name=form.name.data,
            user=current_user
        )
        return redirect(url_for("project.get_all_projects"))
    return render_template("make-project.html", form=form)


@pj_bp.route("/edit-project/<int:project_id>", methods=["GET", "POST"])
@login_required
def edit_project(project_id):
    project = ProjectServices.get_project_by_id(project_id)
    form = SetProjectForm(
        name=project.name
    )
    if form.validate_on_submit():
        new_project = ProjectServices.edit_project(
            name=form.name.data,
            project=project
        )
        return redirect(url_for("project.get_all_projects"))
    return render_template("make-project.html", form=form)


@pj_bp.route("/del-project")
@login_required
def del_project():
    project_id = request.args.get("project_id")
    ProjectServices.del_project(project_id)
    return redirect(url_for("project.get_all_projects"))

app/routes/testcase_route.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.forms import InterfaceTestcaseFrom
from app.services.interface_services import InterfaceServices
from app.services.testcase_services import TestCaseServices
import asyncio

case_route = Blueprint("case", __name__)


@case_route.route("/all-case")
def get_all_case():
    all_case = TestCaseServices.get_all_case()
    return render_template("case.html", all_case=all_case)


@case_route.route("/all-case/<int:interface_id>")
def get_all_case_by_interface(interface_id):
    all_case = TestCaseServices.get_case_by_interface_id(interface_id)
    return render_template("case.html", all_case=all_case)


@case_route.route("/add-case", methods=["GET", "POST"])
def add_case():
    interface_id = request.args.get("interface_id")
    form = InterfaceTestcaseFrom(
        belong_interface=interface_id
    )
    interface_list = InterfaceServices.get_all_interface()
    form.belong_interface.choices = [(interface.id, interface.interface_name) for interface in interface_list]
    if form.validate_on_submit():
        new_case = TestCaseServices.add_case(form)
        return redirect(url_for("interface.show_interface", interface_id=form.belong_interface.data))
    return render_template("make-case.html", form=form)


@case_route.route("/edit-case/<int:case_id>", methods=["GET", "POST"])
def edit_case(case_id):
    case = TestCaseServices.get_case_by_id(case_id)
    form = InterfaceTestcaseFrom(
        testcase_name=case.testcase_name,
        headers=case.headers,
        params=case.params,
        expected_results=case.expected_results,
        description=case.description,
        belong_interface=case.belong_interface_id,
    )
    interface_list = InterfaceServices.get_all_interface()
    form.belong_interface.choices = [(interface.id, interface.interface_name) for interface in interface_list]
    if form.validate_on_submit():
        TestCaseServices.edit_case(case_id, form)
        return redirect(url_for("interface.show_interface", interface_id=form.belong_interface.data))
    return render_template("make-case.html", form=form)


@case_route.route("/del-case")
def del_case():
    case_id = request.args.get("case_id")
    interface_id = request.args.get("interface_id")
    TestCaseServices.del_case(case_id)
    return redirect(url_for("interface.show_interface", interface_id=interface_id))


@case_route.route("/execute-case")
def execute_case():
    is_interface = request.args.get("interface_id")
    if is_interface:
        interface_list = [request.args.get("interface_id")]
        TestCaseServices.execute_case_by_interface(interface_list)
    else:
        case_list = [request.args.get("case_id")]
        TestCaseServices.execute_case_by_case(case_list)
    return redirect(url_for("case.executed_result"))


@case_route.route("/execute-case-result")
def executed_result():
    page = request.args.get("page", 1, type=int)
    pagination = TestCaseServices.get_result_list_page(page=page)
    return render_template("execute-result.html", result_list=pagination)


@case_route.route("/execute-case-result-info/<int:result_id>")
def get_result_list(result_id):
    page = request.args.get("page", 1, type=int)
    result_list = TestCaseServices.get_case_result_page(result_id, page=page)
    return render_template("result-case-list.html", result_list=result_list)


@case_route.route("/show-case-executed-result-info/<int:case_executed_result_id>")
def show_case_executed_result_info(case_executed_result_id):
    result = TestCaseServices.get_case_executed_result_by_id(case_executed_result_id)
    print(result)
    return render_template("result-case-info.html", result=result)

app/templates/add-interface.html
{% include "header.html" %}
{% from "bootstrap5/form.html" import render_form %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
    {{ render_form(form) }}
    </div>
</body>
</html>

app/templates/add-project.html
{% include "header.html" %}
{% from "bootstrap5/form.html" import render_form %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
    {{ render_form(form) }}
    </div>
</body>
</html>

app/templates/base.html
{% include "header.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}
        <!-- Load Bootstrap-Flask CSS here -->
        {{ bootstrap.load_css() }}
        <link
                rel="icon"
                type="image/x-icon"
                href="{{ url_for('static', filename='assets/favicon.ico') }}"
        />
        <!-- Font Awesome icons (free version)-->
        <script
                src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
                crossorigin="anonymous"
        ></script>
        <!-- Google fonts-->
        <link
                href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
                rel="stylesheet"
                type="text/css"
        />
        <link
                href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
                rel="stylesheet"
                type="text/css"
        />
    {% endblock %}
</head>
<body>
{% block content %}{% endblock %}
{{ bootstrap.load_js() }}
</body>
</html>

{% include "footer.html" %}

app/templates/case-info.html
{% include "header.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/execute-result.html
{% extends "base.html" %}
{% from 'bootstrap5/pagination.html' import render_pagination %}
{% block content %}
    <div>
        <h1>测试结果</h1>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">名称</th>
                <th scope="col">执行状态</th>
                <th scope="col">执行数量</th>
                <th scope="col">成功数量</th>
                <th scope="col">失败数量</th>
                <th scope="col">创建时间</th>
                <th scope="col">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for result in result_list %}
                <tr>
                    <th scope="row">{{ result.result_name }}</th>
                    <td>{{ result.status_of_executions }}</td>
                    <td>{{ result.number_of_executions }}</td>
                    <td>{{ result.success_of_executions }}</td>
                    <td>{{ result.fail_of_executions }}</td>
                    <td>{{ result.created_time }}</td>
                    <td><a class="btn btn-primary float-right"
                           href="{{ url_for("case.get_result_list", result_id=result.id) }}">详情</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {{ render_pagination(result_list) }}
{% endblock %}

app/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="footer" class="fixed-bottom start-50">
    {% block footer %}
        &copy; 2025
        <script>new Date().getFullYear() > 2025 && document.write("-" + new Date().getFullYear());</script>,By Ashes .
    {% endblock %}
</div>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}
    首页
{% endblock %}
{% block content %}
    <div>
        <div id="chart"
                {#             class="w-auto h-50"#}
        >
            <!-- 图表将在这里渲染 -->
            {{ html_interface_by_product|safe }}
            <!-- 图表将在这里渲染 -->
            {{ html_testcase_by_interface|safe }}
        </div>
    </div>
{% endblock %}

app/templates/interface-info.html
{% extends "base.html" %}
{% from 'bootstrap5/pagination.html' import render_pagination %}
{% block title %}
	接口详情
{% endblock %}
{% block content %}
    <div>
            <div>
                <h1>接口名称：{{ interface.interface_name }}</h1>
                <p>接口地址：{{ interface.interface_address }}</p>
                <p>接口请求方式：{{ interface.interface_method }}</p>
                <p>接口描述：{{ interface.description }}</p>
                <p>接口所属项目：{{ interface.belong_project.name }}</p>
    {#            <div class="d-flex justify-content-end mb-4">#}
                    <a
                            class="btn btn-primary float-right"
                            href="{{ url_for('case.add_case',interface_id=interface.id) }}"
                    >添加用例</a
                    >
                <a
                            class="btn btn-primary float-right"
                            href="{{ url_for('case.execute_case',interface_id=interface.id) }}"
                    >执行用例</a
                    >
    {#            </div>#}
            </div>
        <div>
        <hr class="my-4"/>
            {% for case in cases %}
                <div>
                    <h3>{{ case.testcase_name }}</h3>
    {#                <div class="d-flex justify-content-end mb-4">#}
                    <a
                                class="btn btn-primary float-right justify-content-end mb-4"
                                href="{{ url_for('case.edit_case',case_id=case.id) }}"
                        >用例详情</a
                        >
                    <a
                                class="btn btn-primary float-right justify-content-end mb-4"
                                href="{{ url_for('case.execute_case',case_id=case.id) }}"
                        >执行用例</a
                        >
                        <a
                                class="btn btn-primary float-right justify-content-end mb-4"
                                href="{{ url_for('case.del_case', case_id=case.id,interface_id=interface.id) }}"
                        >删除用例</a
                        >
    {#                </div>#}
                </div>
                <hr class="my-4"/>
            {% endfor %}
            {{ render_pagination(cases) }}
        </div>
    </div>
{% endblock %}

app/templates/make-case.html
{% extends "base.html" %}
{% from "bootstrap5/form.html" import render_form %}
{% block title %}
	编写用例
{% endblock %}
{% block content %}
    <div>
        {{ render_form(form) }}
    </div>
{% endblock %}

app/templates/make-interface.html
{% extends "base.html" %}
{% from "bootstrap5/form.html" import render_form %}
{% block title %}
	    编写接口
{% endblock %}
{% block content %}
    <div>
    {{ render_form(form) }}
    </div>
{% endblock %}

app/templates/make-project.html
{% extends "base.html" %}
{% from "bootstrap5/form.html" import render_form %}
{% block title %}
	编写项目
{% endblock %}
{% block content %}
    <div>
    {{ render_form(form) }}
    </div>
{% endblock %}

app/templates/project.html
{% extends "base.html" %}
{% from "bootstrap5/form.html" import render_form %}
{% from 'bootstrap5/pagination.html' import render_pagination %}

{% block title %}
    项目
{% endblock %}

{% block content %}
    <div>
        {% if current_user.is_authenticated %}
            <div class="d-flex mb-4">
                <a
                        class="btn btn-primary float-right"
                        href="{{ url_for('project.add_project') }}"
                >创建项目</a
                >
            </div>
        {% endif %}
    </div>
    <div class="row gx-4 gx-lg-5 justify-content-center">
        {% for project in projects %}
            <div>
                <h3 class="d-flex mb-4">项目名称：{{ project.name }}
                    <a class="btn btn-primary float-right"
                       href="{{ url_for("project.edit_project",project_id=project.id) }}">编辑</a>
                    <a class="btn btn-danger float-right"
                       href="{{ url_for("project.del_project",project_id=project.id) }}">删除</a>
                </h3>
            </div>
            <hr class="my-4"/>
        {% endfor %}
    </div>
    <div>
        {{ render_pagination(projects) }}
    </div>
{% endblock %}

app/templates/result-case-info.html
{% extends "base.html" %}
{% from 'bootstrap5/pagination.html' import render_pagination %}
{% block content %}
    <div>
        <h1>测试结果</h1>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">用例名称</th>
                <th scope="col">执行状态</th>
                <th scope="col">操作</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">{{ result.testcase_name }}</th>
                <td>{{ result.execution_status }}</td>
                <td>
                    <a class="btn btn-primary float-right"
                       href="{{ url_for("case.edit_case",case_id=result.testcase_id) }}">编辑</a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

app/templates/result-case-list.html
{% extends "base.html" %}
{% from 'bootstrap5/pagination.html' import render_pagination %}
{% block title %}
    测试结果列表
{% endblock %}
{% block content %}
    <div>
        <h1>测试结果</h1>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">用例名称</th>
                <th scope="col">执行状态</th>
                <th scope="col">创建时间</th>
                <th scope="col">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for result in result_list %}
                <tr>
                    <th scope="row">{{ result.testcase_name }}</th>
                    <td>{{ result.execution_status }}</td>
                    <td>{{ result.created_time }}</td>
                    <td>
                        <a class="btn btn-primary float-right"
                           href="{{ url_for("case.show_case_executed_result_info",case_executed_result_id=result.id) }}">详情</a>
                        <a class="btn btn-primary float-right"
                           href="{{ url_for("case.edit_case",case_id=result.testcase_id) }}">编辑</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {{ render_pagination(result_list) }}
{% endblock %}